Repository pagopa/pagopa-ecommerce-payment-requests-service, pull requests merged in 2023-09, with the labels that each got.

#86 fix(helm-configuration): increase initialDelaySeconds for DEV env
  .DS_Store
  helm/values-dev.yaml
  src/.DS_Store
Labels: size/small, chart-patch, ignore-for-release

#87 Delete .DS_Store
  .DS_Store
  src/.DS_Store
Labels: size/small, skip-release

#88 fix(CR): fixed pipeline duration
  .devops/code-review-pipelines.yml
Labels: size/small, patch, chart-patch

#89 fix(CR pipeline): fixed path collection tests into ecommerce local
  .devops/code-review-pipelines.yml
Labels: size/small, skip-release
