Repository pagopa/pagopa-ecommerce-payment-requests-service, pull requests merged in 2023-07, with the labels that each got.

#74 feat: enable log sending for payment-request
  helm/values-prod.yaml
Labels: size/small

#71 Chk 1694 fix deploy pipeline
  .devops/azure-templates/chart-current-version.yml
  .devops/deploy-pipelines.yml
Labels: size/small

#73 feat(CD): add action to trigger deploy pipeline on push on main branch
  .devops/deploy-pipelines.yml
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yml
  .github/workflows/deploy.yml
  README.md
Labels: skip-release

#75 fix(deploy-pipeline): prod manual approval depends on green api tests
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#76 fix(deploy-pipeline): api test UAT green
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#77 fix(deploy-pipeline): api test UAT green condition
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#61 [CHK-1566] feat(monitoring): use OpenTelemetry monitoring agent instead of Elastic APM
  .env.example
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#78 fix: pr number extraction
  .github/actions/check-pr-semver-labels/action.yml
Labels: size/small, skip-release

#69 CHK-1656 tokenized email for carts (redis cache)
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/pagopa/ecommerce/payment/requests/utils/confidential/ConfidentialDataManager.java
  src/main/java/it/pagopa/ecommerce/payment/requests/utils/confidential/domain/Confidential.java
  src/main/java/it/pagopa/ecommerce/payment/requests/utils/confidential/domain/Email.java
  src/main/java/it/pagopa/ecommerce/payment/requests/utils/confidential/exceptions/ConfidentialDataException.java
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/configurations/confidential/ConfidentialConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/CartService.kt
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/utils/TokenizerEmailUtils.kt
  src/main/resources/application.properties
  src/test/java/it/pagopa/ecommerce/payment/requests/utils/confidential/ConfidentialTest.java
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/configurations/confidential/ConfidentialConfigTests.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/controllers/CartsControllerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/CartsServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/utils/TokenizerEmailUtilsTests.kt
  src/test/resources/application.test.properties
Labels: size/large, minor, chart-minor

#79 fix(mail-validation): make mail validation case insensitive
  src/main/java/it/pagopa/ecommerce/payment/requests/utils/confidential/domain/Email.java
  src/test/java/it/pagopa/ecommerce/payment/requests/utils/confidential/domain/EmailTest.java
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/controllers/CartsControllerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/tests/utils/CartRequests.kt
Labels: size/small, patch, chart-patch

#80 [CHK-1722] - fix(optional-mail): make mail optional
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/CartService.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/controllers/CartsControllerTests.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/CartsServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/tests/utils/CartRequests.kt
Labels: size/small, patch, chart-patch

#81 feat: add Open Telemetry to trace fault code response Chk 1754
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/configurations/openTelemetry/OpenTelemetryConfiguration.kt
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/configurations/openTelemetry/util/OpenTelemetryUtils.kt
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsService.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/configurations/opentelemetry/OpenTelemetryConfigurationTests.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsServiceTests.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/utils/OpenTelemetryUtilsTest.kt
Labels: size/small, patch, chart-patch
