Repository pagopa/pagopa-ecommerce-payment-requests-service, pull requests merged in 2024-05, with the labels that each got.

#100 chore: add beta for testing nodo dev
  .devops/deploy-pipelines.yml
  helm/values-dev.yaml
Labels: size/small, chart-patch, ignore-for-release

#98 CHK-2694: update node error handler
  api-spec/payment-requests-api.yaml
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/errorhandling/ExceptionHandler.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/controllers/PaymentRequestsControllerTests.kt
Labels: size/large, minor, chart-minor

#103 fix: ndots
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/configurations/webclients/WebClientsConfig.kt
Labels: size/small, patch, chart-patch

#101 feat: Add new deployment strategy
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/resources/application.properties
Labels: size/small, patch, chart-patch
