Repository pagopa/pagopa-ecommerce-payment-requests-service, pull requests merged in 2025-04, with the labels that each got.

#120 [CHK-4001] Added api key to pm and psp client
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/client/NodeForPspClient.kt
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/client/NodoPerPmClient.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/clients/NodeForPspClientTests.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/clients/NodoPerPmClientTests.kt
  src/test/resources/application.test.properties
Labels: size/small, minor, chart-minor

#121 [CHK-4001] Helm fix of missing env vars
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#122 chore: revert invoke Node api protected by api key
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/client/NodeForPspClient.kt
  src/main/kotlin/it/pagopa/ecommerce/payment/requests/client/NodoPerPmClient.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/clients/NodeForPspClientTests.kt
  src/test/kotlin/it/pagopa/ecommerce/payment/requests/clients/NodoPerPmClientTests.kt
  src/test/resources/application.test.properties
Labels: size/small, patch, chart-patch

#123 [PIDM-454] fix: expanded prod rollback trigger conditions
  .devops/deploy-pipelines.yml
Labels: size/small, minor, chart-minor

#125 fix: deployment pipeline version bump
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/chart-github-release.yml
  .devops/deploy-pipelines.yml
  .github/workflows/deploy.yml
  .github/workflows/semver_release.yaml
Labels: size/large, patch, chart-patch
